#!/bin/sh
. ../init.sh
run_test_group '
  test-help.sh
  test-list.sh
  test-find-1.sh
  test-find-2.sh
  test-find-3.sh
  test-extract-description-1.sh
  test-extract-description-2.sh
  test-extract-comment-1.sh
  test-extract-comment-2.sh
  test-extract-status-1.sh
  test-extract-status-2.sh
  test-extract-notice-1.sh
  test-extract-notice-2.sh
  test-extract-applicability-1.sh
  test-extract-applicability-2.sh
  test-extract-filelist-1.sh
  test-extract-filelist-2.sh
  test-extract-filelist-3.sh
  test-extract-filelist-4.sh
  test-extract-dependencies-1.sh
  test-extract-dependencies-2.sh
  test-extract-dependencies-3.sh
  test-extract-dependencies-4.sh
  test-extract-recursive-dependencies-1.sh
  test-extract-recursive-dependencies-2.sh
  test-extract-recursive-dependencies-3.sh
  test-extract-dependents-1.sh
  test-extract-dependents-2.sh
  test-extract-dependents-3.sh
  test-extract-dependents-4.sh
  test-extract-autoconf-snippet-1.sh
  test-extract-autoconf-snippet-2.sh
  test-extract-autoconf-snippet-3.sh
  test-extract-automake-snippet-1.sh
  test-extract-automake-snippet-2.sh
  test-extract-automake-snippet-3.sh
  test-extract-include-directive-1.sh
  test-extract-include-directive-2.sh
  test-extract-include-directive-3.sh
  test-extract-include-directive-4.sh
  test-extract-link-directive-1.sh
  test-extract-link-directive-2.sh
  test-extract-link-directive-3.sh
  test-extract-link-directive-4.sh
  test-extract-recursive-link-directive-1.sh
  test-extract-recursive-link-directive-2.sh
  test-extract-recursive-link-directive-3.sh
  test-extract-recursive-link-directive-4.sh
  test-extract-license-1.sh
  test-extract-license-2.sh
  test-extract-license-3.sh
  test-extract-license-4.sh
  test-extract-license-5.sh
  test-extract-license-6.sh
  test-extract-maintainer-1.sh
  test-extract-maintainer-2.sh
  test-extract-maintainer-3.sh
  test-extract-tests-module-1.sh
  test-extract-tests-module-2.sh
  test-extract-tests-module-3.sh
'
