#!/bin/sh
. ../init.sh
# This tests a hairy case: A file, gnulib-tests/nan.h, that previously came
# from gnulib/tests/ and now comes from gnulib/lib/. It should not be shown
# as a removed and added file, but rather as a changed file, with no effect
# on gnulib-tests/.gitignore.
do_import_test diffutils-20230801 . "`echo '
  --import
  --local-dir=gl
  --lib=libdiffutils
  --source-base=lib
  --m4-base=m4
  --doc-base=doc
  --tests-base=gnulib-tests
  --aux-dir=build-aux
  --with-tests
  --makefile-name=gnulib.mk
  --no-conditional-dependencies
  --no-libtool
  --macro-prefix=gl
  --avoid=localename
  --avoid=lock-tests
  --avoid=setlocale
  announce-gen
  argmatch
  assert-h
  attribute
  binary-io
  builtin-expect
  c-ctype
  c-stack
  c32isspace
  c32tolower
  c32width
  careadlinkat
  config-h
  count-leading-zeros
  diffseq
  dirname
  do-release-commit-and-tag
  dup2
  error
  exclude
  exitfail
  extensions
  extern-inline
  fcntl
  fdopendir
  file-type
  filenamecat
  flexmember
  fnmatch-gnu
  fstatat
  getopt-gnu
  gettext-h
  git-version-gen
  gitlog-to-changelog
  gnu-make
  gnu-web-doc-update
  gnumakefile
  gnupload
  hard-locale
  ialloc
  idx
  intprops
  inttypes
  isblank
  largefile
  lstat
  maintainer-makefile
  manywarnings
  mbrtoc32
  mempcpy
  minmax
  mkstemp
  mktime
  nstrftime
  nullptr
  openat
  pclose
  perl
  popen
  progname
  propername-lite
  raise
  rawmemchr
  readdir
  readlinkat
  readme-release
  regex
  same-inode
  sh-quote
  sigaction
  signal
  sigprocmask
  stat
  stat-macros
  stat-time
  stdbool
  stdckdint
  stdint
  stpcpy
  strcase
  strptime
  strtoimax
  sys_wait
  system-quote
  time_rz
  timespec
  timespec_get
  unistd
  unlocked-io
  update-copyright
  verify
  version-etc
  version-etc-fsf
  xalloc
  xfreopen
  xmalloca
  xstdopen
  xstrtoimax
  year2038

'`"
