#!/bin/sh
. ../init.sh
do_import_test gettext-20240101 . "`echo '
  --dir=gettext-tools
  --source-base=libgettextpo
  --m4-base=libgettextpo/gnulib-m4
  --macro-prefix=gtpo
  --makefile-name=Makefile.gnulib
  --libtool
  --local-dir=gnulib-local
  --import
  --avoid=progname
  attribute
  basename-lgpl
  close
  c-ctype
  c-strcase
  c-strstr
  error
  error-progname
  filename
  fopen
  free-posix
  fstrcmp
  fwriteerror
  gcd
  getline
  gettext-h
  iconv
  libtextstyle-dummy
  libunistring-optional
  markup
  mem-hash-map
  minmax
  open
  relocatable-lib
  sigpipe
  stdbool
  stdio
  stdlib
  stpcpy
  stpncpy
  strchrnul
  strerror
  string-desc
  unictype/ctype-space
  unilbrk/ulc-width-linebreaks
  unistr/u8-mbtouc
  unistr/u8-mbtoucr
  unistr/u8-uctomb
  unistr/u16-mbtouc
  uniwidth/width
  unlocked-io
  vasprintf
  xalloc
  xconcat-filename
  xmalloca
  xerror
  xstriconv
  xvasprintf
  fdopen
  realloc-posix
  strerror_r-posix
'`"
